import "server-only";
import { mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { Database } from "bun:sqlite";
import { drizzle } from "drizzle-orm/bun-sqlite";
import { migrate } from "drizzle-orm/bun-sqlite/migrator";
import { env } from "@/src/server/env";
import * as schema from "@/src/server/db/schema";

const open = () => {
  mkdirSync(dirname(env.DATABASE_PATH), { recursive: true });
  const sqlite = new Database(env.DATABASE_PATH, { create: true });
  sqlite.run("PRAGMA busy_timeout = 5000;"); // before WAL, so conversion waits instead of failing
  sqlite.run("PRAGMA journal_mode = WAL;");
  sqlite.run("PRAGMA foreign_keys = ON;"); // isForeignKeyViolation relies on this
  const instance = drizzle(sqlite, { schema });
  // Generated by `bun run db:generate`, applied on first runtime import.
  migrate(instance, { migrationsFolder: "drizzle" });
  return instance;
};

// `next build` imports route modules only to collect metadata — never touch
// the database then.
const db: ReturnType<typeof open> =
  process.env.NEXT_PHASE === "phase-production-build"
    ? (undefined as never)
    : open();

export { db };
