import "server-only";
import { mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { Database } from "bun:sqlite";
import { drizzle } from "drizzle-orm/bun-sqlite";
import { migrate } from "drizzle-orm/bun-sqlite/migrator";
import { env } from "@/src/server/env";
import * as schema from "@/src/server/db/schema";

mkdirSync(dirname(env.DATABASE_PATH), { recursive: true });

const sqlite = new Database(env.DATABASE_PATH, { create: true });
sqlite.exec("PRAGMA journal_mode = WAL;");
sqlite.exec("PRAGMA busy_timeout = 5000;");
sqlite.exec("PRAGMA foreign_keys = ON;"); // isForeignKeyViolation relies on this

const db = drizzle(sqlite, { schema });

// Generated by `bun run db:generate`, applied on first import.
migrate(db, { migrationsFolder: "drizzle" });

export { db };
